FROM python:3.9-slim-buster

ENV LIDARR_RUN_SCRIPT=1
ENV RADARR_RUN_SCRIPT=1
ENV READARR_RUN_SCRIPT=1
ENV SONARR_RUN_SCRIPT=1
ENV WHISPARR_RUN_SCRIPT=1
ENV LIDARR_URL='http://lidarr:7878'
ENV LIDARR_API_KEY=123456
ENV RADARR_URL='http://radarr:7878'
ENV RADARR_API_KEY=123456
ENV READARR_URL='http://readarr:7878'
ENV READARR_API_KEY=123456
ENV SONARR_URL='http://sonarr:8989'
ENV SONARR_API_KEY=123456
ENV WHISPARR_URL='http://whisparr:7878'
ENV WHISPARR_API_KEY=123456
ENV API_TIMEOUT=600

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "cleaner.py"]
